version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: weather
    environment:
      DB_CONNECTION_URL: jdbc:postgresql://db:5432/weather
      DB_CONNECTION_USERNAME: postgres
      DB_CONNECTION_PASSWORD: root

volumes:
  postgres_data: